[package]
name = "ani-well-backend"
version = { workspace = true }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ani_well_backend_lib"
crate-type = ["rlib"]

[dependencies]
axum = "0.7.5"
serde = "1.0.203"
serde_json = "1.0.117"
